spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:reconx}
    username: ${POSTGRES_USER:reconx_user}
    password: ${POSTGRES_PASSWORD:reconx_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
logging:
  level:
    com.dbtraining.reconx: INFO
management:
  endpoint:
    health:
      show-details: always